# Generated by Django 4.1 on 2022-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.CharField(default='superadmin', max_length=20),
        ),
    ]
