# Generated by Django 4.1 on 2022-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
